[project]
name = "foursquare-feeds"
version = "2.3.1"
description = "A python script for generating an iCal feed from your Foursquare checkins"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"caldav>=2.0.1",
	"foursquare",
	"ics",
	"simplekml",
]
